---
language: cpp
sudo: false

env:
  - PLATFORM=arduino:avr:leonardo
  - PLATFORM=arduino:avr:uno
  - PLATFORM=arduino:sam:arduino_due_x
  - PLATFORM=arduino:samd:arduino_zero_native

matrix:
  fast_finish: true

before_install:
  - source <(curl -SLs https://gist.githubusercontent.com/tomasbasham/e9ace873c23f8f0f00cd31b22f141111/raw) # install.sh

script:
  - build_examples

notifications:
  email: false
  slack:
    secure: "qiOWt2ODAbSENja5yyx6sBFzuRkkuVme8I3WI+gBEDZBAcHsPXwAZ3zQsjoo6a+RdJHJHBz3xxV163R8b/uKmS++VAbzJNvaMqPbfvOn9wNDY+BgmCec8GAZACByJSHi25mTr/9wJzTvkH6RcVw+/KfV3casuZxHjxEXPfW+Rks="
